worker_processes auto;

events {
  worker_connections 1024;
}

http {
  upstream techcorp_api {
    server ffl-api-1:8080;
    server ffl-api-2:8080;
    server ffl-api-3:8080;
    server ffl-api-4:8080;
    server ffl-api-5:8080;
    server ffl-api-6:8080;
    server ffl-api-7:8080;
    server ffl-api-8:8080;
    server ffl-api-9:8080;
    server ffl-api-10:8080;
  }

  server {
    listen 80;

    add_header X-Served-By $upstream_addr always;

    location / {
      proxy_pass http://techcorp_api;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}